version: '2'

services:
  backend:
    container_name: sample_api
    build: .
    ports:
     - "9999"
    volumes:
     - .:/src
    networks: 
      - network

  mongo:
    container_name: sample_mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks: 
      - network
networks:
    network:
        driver: bridge
