version: '2'

services:
  backend:
    container_name: sample_api
    build: .
    ports:
     - "9999"
    networks: 
      - network

  mongo:
    container_name: sample_mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks: 
      - network
    volumes:
      # So we can start off with data in our db
      - .data:/data/db

networks:
    network:
        driver: bridge
